// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.hitosea.com/",
        "contact": {},
        "license": {
            "name": "AGPL-3.0 license",
            "url": "http://www.gnu.org/licenses/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/doo/user/info": {
            "get": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Dootask"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/okr/create": {
            "post": {
                "description": "创建OKR",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Okr"
                ],
                "summary": "创建OKR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标",
                        "name": "Title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "对齐目标",
                        "name": "align_objective",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "归属 1-部门 2-个人",
                        "name": "ascription",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "优先级",
                        "name": "priority",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类型 1-承诺型 2-挑战型",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "可见范围  1-全公司 2-仅相关成员 3-仅部门成员",
                        "name": "visible_range",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/okr/follow/list": {
            "get": {
                "description": "关注的OKR列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Okr"
                ],
                "summary": "关注的OKR列表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标",
                        "name": "objective",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/okr/my/list": {
            "get": {
                "description": "我的OKR列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Okr"
                ],
                "summary": "我的OKR列表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标",
                        "name": "objective",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/okr/participant/list": {
            "get": {
                "description": "参与的OKR列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Okr"
                ],
                "summary": "参与的OKR列表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标",
                        "name": "objective",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        },
        "/okr/update": {
            "post": {
                "description": "更新OKR",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Okr"
                ],
                "summary": "更新OKR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "对齐目标",
                        "name": "align_objective",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标",
                        "name": "objective",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "优先级",
                        "name": "priority",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_at",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类型 1-承诺型 2-挑战型",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "可见范围  1-全公司 2-仅相关成员 3-仅部门成员",
                        "name": "visible_range",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "interfaces.OkrKeyResultCreateReq": {
            "type": "object",
            "required": [
                "confidence",
                "end_at",
                "participant",
                "start_at",
                "title"
            ],
            "properties": {
                "confidence": {
                    "description": "信心指数",
                    "type": "integer"
                },
                "end_at": {
                    "description": "结束时间",
                    "type": "string"
                },
                "participant": {
                    "description": "参与人,多个用逗号隔开",
                    "type": "string"
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string"
                },
                "title": {
                    "description": "关键结果",
                    "type": "string"
                }
            }
        },
        "interfaces.OkrKeyResultUpdateReq": {
            "type": "object",
            "required": [
                "confidence",
                "end_at",
                "id",
                "key_result",
                "participant",
                "start_at"
            ],
            "properties": {
                "confidence": {
                    "description": "信心指数",
                    "type": "integer"
                },
                "end_at": {
                    "description": "结束时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "key_result": {
                    "description": "关键结果",
                    "type": "string"
                },
                "participant": {
                    "description": "参与人,多个用逗号隔开",
                    "type": "string"
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string"
                }
            }
        },
        "interfaces.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许, 500=系统错误]",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "信息",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "http://localhost",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "DooTask",
	Description: "DooTask是一款轻量级的开源在线项目任务管理工具，提供各类文档协作工具、在线思维导图、在线流程图、项目管理、任务分发、即时IM，文件管理等工具。",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
