basePath: /api/v1
definitions:
  interfaces.OkrAnalyzeDept:
    properties:
      complete:
        description: okr 完成数
        type: integer
      department_id:
        description: 部门id
        type: integer
      department_name:
        description: 部门名称
        type: string
      total:
        description: okr 总数
        type: integer
    type: object
  interfaces.OkrAnalyzeDeptScoreProportion:
    properties:
      already_reviewed:
        description: 已评分
        type: integer
      department_id:
        description: 部门id
        type: integer
      department_name:
        description: 部门名称
        type: string
      total:
        description: okr 总数
        type: integer
      unscored:
        description: 未评分
        type: integer
    type: object
  interfaces.OkrAnalyzeOverall:
    properties:
      complete:
        description: okr 完成数
        type: integer
      total:
        description: okr 总数
        type: integer
    type: object
  interfaces.OkrAnalyzePersonnelScoreRate:
    properties:
      complete:
        description: okr 完成数
        type: integer
      total:
        description: okr 总数
        type: integer
    type: object
  interfaces.OkrAnalyzeScore:
    properties:
      seven_to_ten:
        description: 7-10分
        type: integer
      three_to_seven:
        description: 3-7分
        type: integer
      total:
        description: okr 总数
        type: integer
      unscored:
        description: 未评分
        type: integer
      zero_to_three:
        description: 0-3分
        type: integer
    type: object
  interfaces.OkrAnalyzeScoreDept:
    properties:
      department_id:
        description: 部门id
        type: integer
      department_name:
        description: 部门名称
        type: string
      seven_to_ten:
        description: 7-10分
        type: integer
      three_to_seven:
        description: 3-7分
        type: integer
      total:
        description: okr 总数
        type: integer
      unscored:
        description: 未评分
        type: integer
      zero_to_three:
        description: 0-3分
        type: integer
    type: object
  interfaces.OkrCreateReq:
    properties:
      align_objective:
        description: 对齐目标
        type: string
      ascription:
        description: 归属 1-部门 2-个人
        type: integer
      end_at:
        description: 结束时间
        type: string
      key_results:
        description: 关键结果
        items:
          $ref: '#/definitions/interfaces.OkrKeyResultCreateReq'
        type: array
      priority:
        description: 优先级
        type: string
      project_id:
        description: 项目id
        type: integer
      start_at:
        description: 开始时间
        type: string
      title:
        description: 目标
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      visible_range:
        description: 可见范围  1-全公司 2-仅相关成员 3-仅部门成员
        type: integer
    required:
    - align_objective
    - ascription
    - end_at
    - key_results
    - priority
    - project_id
    - start_at
    - title
    - type
    - visible_range
    type: object
  interfaces.OkrDepartmentListReq:
    properties:
      completed:
        description: 是否已完成未评分 0-未完成 1-已完成
        type: integer
      department_id:
        description: 部门id
        type: integer
      end_at:
        description: 结束时间
        type: string
      objective:
        description: 目标
        type: string
      start_at:
        description: 开始时间
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      userid:
        description: 用户id
        type: integer
    type: object
  interfaces.OkrKeyResultCreateReq:
    properties:
      confidence:
        description: 信心指数
        type: integer
      end_at:
        description: 结束时间
        type: string
      participant:
        description: 参与人,多个用逗号隔开
        type: string
      start_at:
        description: 开始时间
        type: string
      title:
        description: 关键结果
        type: string
    required:
    - confidence
    - end_at
    - participant
    - start_at
    - title
    type: object
  interfaces.OkrKeyResultUpdateReq:
    properties:
      confidence:
        description: 信心指数
        type: integer
      end_at:
        description: 结束时间
        type: string
      id:
        description: id
        type: integer
      participant:
        description: 参与人,多个用逗号隔开
        type: string
      start_at:
        description: 开始时间
        type: string
      title:
        description: 关键结果
        type: string
    required:
    - confidence
    - end_at
    - id
    - participant
    - start_at
    - title
    type: object
  interfaces.OkrReplayComment:
    properties:
      comment:
        description: 评价
        type: string
      id:
        description: id
        type: integer
    required:
    - id
    type: object
  interfaces.OkrReplayCreateReq:
    properties:
      comments:
        description: 复盘评价
        items:
          $ref: '#/definitions/interfaces.OkrReplayComment'
        type: array
      id:
        description: id
        type: integer
      problem:
        description: 问题与不足
        type: string
      value:
        description: 价值与收获
        type: string
    required:
    - id
    type: object
  interfaces.OkrUpdateReq:
    properties:
      align_objective:
        description: 对齐目标
        type: string
      end_at:
        description: 结束时间
        type: string
      id:
        description: id
        type: integer
      key_results:
        description: 关键结果
        items:
          $ref: '#/definitions/interfaces.OkrKeyResultUpdateReq'
        type: array
      priority:
        description: 优先级
        type: string
      project_id:
        description: 项目id
        type: integer
      start_at:
        description: 开始时间
        type: string
      title:
        description: 目标
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      visible_range:
        description: 可见范围  1-全公司 2-仅相关成员 3-仅部门成员
        type: integer
    required:
    - align_objective
    - end_at
    - id
    - key_results
    - priority
    - project_id
    - start_at
    - title
    - type
    - visible_range
    type: object
  interfaces.Response:
    properties:
      code:
        description: 状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许,
          500=系统错误]
        type: integer
      data:
        description: 数据
      msg:
        description: 信息
        type: string
    type: object
host: http://localhost
info:
  contact: {}
  description: DooTask是一款轻量级的开源在线项目任务管理工具，提供各类文档协作工具、在线思维导图、在线流程图、项目管理、任务分发、即时IM，文件管理等工具。
  license:
    name: AGPL-3.0 license
    url: http://www.gnu.org/licenses/
  termsOfService: https://www.hitosea.com/
  title: DooTask
  version: "1.0"
paths:
  /doo/project/list:
    get:
      consumes:
      - application/json
      description: 获取项目列表
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 获取项目列表
      tags:
      - Dootask
  /doo/user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 获取用户信息
      tags:
      - Dootask
  /doo/user/list:
    get:
      consumes:
      - application/json
      description: 获取用户列表
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 获取用户列表
      tags:
      - Dootask
  /okr/analyze/complete:
    get:
      consumes:
      - application/json
      description: OKR整体平均完成度
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  $ref: '#/definitions/interfaces.OkrAnalyzeOverall'
              type: object
      summary: OKR整体平均完成度
      tags:
      - OkrAnalyze
  /okr/analyze/dept/complete:
    get:
      consumes:
      - application/json
      description: OKR各部门平均完成度
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/interfaces.OkrAnalyzeDept'
                  type: array
              type: object
      summary: OKR各部门平均完成度
      tags:
      - OkrAnalyze
  /okr/analyze/dept/score:
    get:
      consumes:
      - application/json
      description: OKR各部门评分分布
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  $ref: '#/definitions/interfaces.OkrAnalyzeScoreDept'
              type: object
      summary: OKR各部门评分分布
      tags:
      - OkrAnalyze
  /okr/analyze/dept/score/proportion:
    get:
      consumes:
      - application/json
      description: OKR部门评分占比
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/interfaces.OkrAnalyzeDeptScoreProportion'
                  type: array
              type: object
      summary: OKR各部门评分占比
      tags:
      - OkrAnalyze
  /okr/analyze/personnel/score/rate:
    get:
      consumes:
      - application/json
      description: OKR人员评分率
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  $ref: '#/definitions/interfaces.OkrAnalyzePersonnelScoreRate'
              type: object
      summary: OKR人员评分率
      tags:
      - OkrAnalyze
  /okr/analyze/score:
    get:
      consumes:
      - application/json
      description: OKR评分分布
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/interfaces.Response'
            - properties:
                data:
                  $ref: '#/definitions/interfaces.OkrAnalyzeScore'
              type: object
      summary: OKR评分分布
      tags:
      - OkrAnalyze
  /okr/confidence/update:
    post:
      consumes:
      - application/json
      description: 更新信心指数
      parameters:
      - description: 信心指数
        in: formData
        name: confidence
        required: true
        type: integer
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 更新信心指数
      tags:
      - Okr
  /okr/create:
    post:
      consumes:
      - application/json
      description: 创建OKR
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 创建OKR
      tags:
      - Okr
  /okr/department/list:
    get:
      consumes:
      - application/json
      description: 部门OKR列表
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrDepartmentListReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 部门OKR列表
      tags:
      - Okr
  /okr/finish:
    post:
      consumes:
      - application/json
      description: 结束/重启目标
      parameters:
      - description: 状态 0-重启 1-结束
        in: formData
        name: finished
        type: integer
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 结束/重启目标
      tags:
      - Okr
  /okr/follow:
    get:
      consumes:
      - application/json
      description: 关注或取消关注目标
      parameters:
      - description: 目标id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 关注或取消关注目标
      tags:
      - Okr
  /okr/follow/list:
    get:
      consumes:
      - application/json
      description: 关注的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 关注的OKR列表
      tags:
      - Okr
  /okr/my/list:
    get:
      consumes:
      - application/json
      description: 我的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 我的OKR列表
      tags:
      - Okr
  /okr/participant/list:
    get:
      consumes:
      - application/json
      description: 参与的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 参与的OKR列表
      tags:
      - Okr
  /okr/participant/update:
    post:
      consumes:
      - application/json
      description: 更新参与人
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: 参与人,多个用逗号隔开
        in: formData
        name: participant
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 更新参与人
      tags:
      - Okr
  /okr/replay/create:
    post:
      consumes:
      - application/json
      description: 添加复盘
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrReplayCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 添加复盘
      tags:
      - Okr
  /okr/replay/detail:
    get:
      consumes:
      - application/json
      description: 复盘详情
      parameters:
      - description: 复盘id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 复盘详情
      tags:
      - Okr
  /okr/replay/list:
    get:
      consumes:
      - application/json
      description: OKR复盘列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: OKR复盘列表
      tags:
      - Okr
  /okr/score:
    post:
      consumes:
      - application/json
      description: OKR评分
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: 个人评分
        in: formData
        name: score
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: OKR评分
      tags:
      - Okr
  /okr/update:
    post:
      consumes:
      - application/json
      description: 更新OKR
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 更新OKR
      tags:
      - Okr
  /okr/update/progress:
    post:
      consumes:
      - application/json
      description: 更新进度和进度状态
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: 进度
        in: formData
        name: progress
        type: integer
      - description: 进度状态 0-默认 1-正常 2-有风险 3-延期 4-已结束
        in: formData
        name: status
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 更新进度和进度状态
      tags:
      - Okr
swagger: "2.0"
