basePath: /api/v1
definitions:
  interfaces.OkrCreateReq:
    properties:
      align_objective:
        description: 对齐目标
        type: string
      ascription:
        description: 归属 1-部门 2-个人
        type: integer
      end_at:
        description: 结束时间
        type: string
      key_results:
        description: 关键结果
        items:
          $ref: '#/definitions/interfaces.OkrKeyResultCreateReq'
        type: array
      priority:
        description: 优先级
        type: string
      project_id:
        description: 项目id
        type: integer
      start_at:
        description: 开始时间
        type: string
      title:
        description: 目标
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      visible_range:
        description: 可见范围  1-全公司 2-仅相关成员 3-仅部门成员
        type: integer
    required:
    - align_objective
    - ascription
    - end_at
    - key_results
    - priority
    - project_id
    - start_at
    - title
    - type
    - visible_range
    type: object
  interfaces.OkrDepartmentListReq:
    properties:
      completed:
        description: 是否已完成未评分 0-未完成 1-已完成
        type: integer
      department_id:
        description: 部门id
        type: integer
      end_at:
        description: 结束时间
        type: string
      objective:
        description: 目标
        type: string
      start_at:
        description: 开始时间
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      userid:
        description: 用户id
        type: integer
    type: object
  interfaces.OkrKeyResultCreateReq:
    properties:
      confidence:
        description: 信心指数
        type: integer
      end_at:
        description: 结束时间
        type: string
      participant:
        description: 参与人,多个用逗号隔开
        type: string
      start_at:
        description: 开始时间
        type: string
      title:
        description: 关键结果
        type: string
    required:
    - confidence
    - end_at
    - participant
    - start_at
    - title
    type: object
  interfaces.OkrKeyResultUpdateReq:
    properties:
      confidence:
        description: 信心指数
        type: integer
      end_at:
        description: 结束时间
        type: string
      id:
        description: id
        type: integer
      participant:
        description: 参与人,多个用逗号隔开
        type: string
      start_at:
        description: 开始时间
        type: string
      title:
        description: 关键结果
        type: string
    required:
    - confidence
    - end_at
    - id
    - participant
    - start_at
    - title
    type: object
  interfaces.OkrUpdateReq:
    properties:
      align_objective:
        description: 对齐目标
        type: string
      end_at:
        description: 结束时间
        type: string
      id:
        description: id
        type: integer
      key_results:
        description: 关键结果
        items:
          $ref: '#/definitions/interfaces.OkrKeyResultUpdateReq'
        type: array
      priority:
        description: 优先级
        type: string
      project_id:
        description: 项目id
        type: integer
      start_at:
        description: 开始时间
        type: string
      title:
        description: 目标
        type: string
      type:
        description: 类型 1-承诺型 2-挑战型
        type: integer
      visible_range:
        description: 可见范围  1-全公司 2-仅相关成员 3-仅部门成员
        type: integer
    required:
    - align_objective
    - end_at
    - id
    - key_results
    - priority
    - project_id
    - start_at
    - title
    - type
    - visible_range
    type: object
  interfaces.Response:
    properties:
      code:
        description: 状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许,
          500=系统错误]
        type: integer
      data:
        description: 数据
      msg:
        description: 信息
        type: string
    type: object
host: http://localhost
info:
  contact: {}
  description: DooTask是一款轻量级的开源在线项目任务管理工具，提供各类文档协作工具、在线思维导图、在线流程图、项目管理、任务分发、即时IM，文件管理等工具。
  license:
    name: AGPL-3.0 license
    url: http://www.gnu.org/licenses/
  termsOfService: https://www.hitosea.com/
  title: DooTask
  version: "1.0"
paths:
  /doo/user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 获取用户信息
      tags:
      - Dootask
  /okr/create:
    post:
      consumes:
      - application/json
      description: 创建OKR
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 创建OKR
      tags:
      - Okr
  /okr/department/list:
    get:
      consumes:
      - application/json
      description: 部门OKR列表
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrDepartmentListReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 部门OKR列表
      tags:
      - Okr
  /okr/follow/list:
    get:
      consumes:
      - application/json
      description: 关注的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 关注的OKR列表
      tags:
      - Okr
  /okr/my/list:
    get:
      consumes:
      - application/json
      description: 我的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 我的OKR列表
      tags:
      - Okr
  /okr/participant/list:
    get:
      consumes:
      - application/json
      description: 参与的OKR列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 参与的OKR列表
      tags:
      - Okr
  /okr/replay/list:
    get:
      consumes:
      - application/json
      description: OKR复盘列表
      parameters:
      - description: 目标
        in: query
        name: objective
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: OKR复盘列表
      tags:
      - Okr
  /okr/update:
    post:
      consumes:
      - application/json
      description: 更新OKR
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 更新OKR
      tags:
      - Okr
swagger: "2.0"
