basePath: /api/v1
definitions:
  interfaces.OkrAddReq:
    properties:
      content:
        description: 内容
        type: string
      parent_id:
        description: 父级ID
        type: integer
      title:
        description: 标题
        type: string
    required:
    - content
    - parent_id
    - title
    type: object
  interfaces.Response:
    properties:
      code:
        description: 状态, [200=成功, 400=失败, 401=未登录, 403=无相关权限, 404=请求接口不存在, 405=请求方法不允许,
          500=系统错误]
        type: integer
      data:
        description: 数据
      msg:
        description: 信息
        type: string
    type: object
host: http://localhost
info:
  contact: {}
  description: DooTask是一款轻量级的开源在线项目任务管理工具，提供各类文档协作工具、在线思维导图、在线流程图、项目管理、任务分发、即时IM，文件管理等工具。
  license:
    name: AGPL-3.0 license
    url: http://www.gnu.org/licenses/
  termsOfService: https://www.hitosea.com/
  title: DooTask
  version: "1.0"
paths:
  /okr/add:
    post:
      consumes:
      - application/json
      description: 创建OKR
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.OkrAddReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Response'
      summary: 创建OKR
      tags:
      - Okr
swagger: "2.0"
